config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :lectures do
    member do
      put "like", to: "lectures#like"
      put "unlike", to: "lectures#unlike"
      get :spam
    end
  end
  resources :courses
  resources :comments
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.role == "instructor"
     can [:read, :create], Course
     can [:read,:create, :like,:unlike, :spam], Lecture     
     can [:update, :destroy], Course, :user_id => user.id
     can [:update, :destroy], Lecture, :course => { :user_id => user.id }
    
    elsif user.role == "user"
      can :read, Course
      can [:read,:like, :unlike, :spam], Lecture   
    else
      can :read, Course
      can :read, Lecture
  end 
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/course.rb
class Course < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :user_id, presence: true
    belongs_to :user
    has_many :lectures, dependent: :destroy

end

app/models/lecture.rb
class Lecture < ApplicationRecord
    validates :attachment, file_size: { less_than: 1.megabytes }
    validates_uniqueness_of :title, scope: :course_id
    validates :title , presence: true
    mount_uploader :attachment, AttachmentUploader
    belongs_to :course
    has_and_belongs_to_many :users
    acts_as_votable
    acts_as_commentable

    def spam!(user)
        if !spam?(user)
        self.users<< user
        end
    end

    def spam?(user)
        self.users.include? user
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum gender: {male: 0, female: 1, any: 2}
  validates :profile_picture, file_size: { less_than: 1.megabytes }
  mount_uploader :profile_picture, ImageUploader
  ROLES = %w[instructor user].freeze
  has_many :courses, dependent: :destroy
  has_and_belongs_to_many :lectures
  acts_as_voter
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to courses_url, notice: exception.message
  end
  protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :date_of_birth, :gender, :profile_picture, :role) }
          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :date_of_birth, :gender, :profile_picture) }
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
  before_action :authenticate_user!

  def create
    commentable = commentable_type.constantize.find(commentable_id)
    @comment = Comment.build_from(commentable, current_user.id, body)

    respond_to do |format|
      if @comment.save
        make_child_comment
        format.html  { redirect_back(fallback_location: root_path,:notice => 'Comment was successfully added.') }
      else
        format.html  { render :action => "new" }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id)
  end

  def commentable_type
    comment_params[:commentable_type]
  end

  def commentable_id
    comment_params[:commentable_id]
  end

  def comment_id
    comment_params[:comment_id]
  end

  def body
    comment_params[:body]
  end

  def make_child_comment
    return "" if comment_id.blank?

    parent_comment = Comment.find comment_id
    @comment.move_to_child_of(parent_comment)
  end

end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  load_and_authorize_resource
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    if @course.save
      redirect_to @course
    else
      render :new
    end
  end
  private

    def course_params
      params.require(:course).permit(:title)
    end
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  load_and_authorize_resource 
  
  
  def show
    @lecture= Lecture.find(params[:id])
    if current_user
    @new_comment = Comment.build_from(@lecture, current_user.id, "")
    end
  end
  def like
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_by current_user
    render layout: false
  end
  def unlike
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_from current_user
    render layout: false
  end
  def spam
    @lecture = Lecture.find(params[:id])
    @lecture.spam!(current_user)
    redirect_to lecture_path(@lecture )
  end
  private

    def lecture_params
      params.require(:lecture).permit(:content, :attachment, :course_id, :title )
    end

    

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>  
  <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
  <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
  <div class="field form-group">
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= submit_tag "Post comment", class: 'btn btn-primary' %>
  </div>
<% end %>  

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>
  <div class="comments-show">
    <div class="comment">
      <p><%= comment.body %> by <%= comment.user.name %><br></p>
      <% if user_signed_in? %>
      <div class="comment-nav"><a  class="comment-reply">reply</a></div>
      <div class="reply-form">
        <%= form_for @new_comment do |f| %>
          <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
          <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
          <%= f.hidden_field :comment_id, value: comment.id %>
          <div class="field form-group">
            <%= f.text_area :body, class: 'form-control' %>
          </div>
          <div class="field form-group">
            <%= submit_tag "Post Reply", class: 'btn btn-primary' %>
          </div>
        <% end %>
          
       
      </div>
       <% end %>
    </div>
    <%= render partial: "comments/reply", locals: {comments: comment.children} %>
  </div>
<% end %> 

app/views/comments/_template.html.erb
<div class="comments-header">  
  <h4>
    <%= commentable.comment_threads.count == 0 ? "no" : commentable.comment_threads.count %> comments
  </h4>
</div>
      <% if user_signed_in? %>
<%= render partial: "comments/form", locals: {new_comment: new_comment} %>
<% end %>  
<div class="comments-container">  
  <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
</div>  

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true, html: {class: 'form-horizontal'}  ) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field form-group">
    <%= form.label :title , class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= form.text_field :title, id: :course_title, class: 'form-control' %>
    </div>
  </div>
 
  <div class="actions form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= form.submit 'Submit', :class=> 'btn btn-primary'%>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table  class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to  course , class: "btn btn-info" do %>
  <i class="fa fa-info-circle"></i> show
<% end %>
        <% if can? :update, course %>
        <%= link_to  edit_course_path(course), class: "btn btn-warning" do %>
        <i class="fa fa-edit"></i> Edit
      <% end %>
        <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do %>
  <i class="fa fa-times"></i> Delete
<% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Course %>
<%= link_to  new_course_path, class: "btn btn-primary" do %>
  <i class="fa fa-plus"></i> New Course
<% end %>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card ">
<div class="card-header bg-info text-white">
<h2><%= @course.title %> </h2>
</div>
 <div class="card-body">
<div class="card-text">
<div class="container">
<h1>Course lectures:</h1>
<ul class="list-group">
<% @course.lectures.each do |lecture| %>
  <li class="list-group-item list-group-item-action"><%= link_to lecture.title, lecture %></li>
<% end %>
</ul>
</div>
<br/>
<% if can? :update, @course %>
<%= link_to  edit_course_path(@course) , class: "btn btn-warning" do %>
        <i class="fa fa-edit"></i> Edit Course
      <% end %>   |
<%= link_to @course, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger" do %>
  <i class="fa fa-times"></i> Delete Course
<% end %>  |
<%= link_to new_lecture_path , class: "btn btn-primary" do %>
  <i class="fa fa-plus"></i> New Lecture
<% end %> 
<% end  %>
</div>
</div>
</div>
<%= link_to 'Back', courses_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ">
    <%= image_tag("logo1.png", alt: 'LOGO',:size => "80x40")%>
      <%= link_to "Home", root_path, class: 'nav-link' %>
              <%= link_to "courses", courses_path, class: 'nav-link' %>
              <%= link_to "Lectures", lectures_path, class: 'nav-link' %>
      <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link' ) %>        
        </li>
        <% else %>
        <li>
        <%= link_to('Login', new_user_session_path, class: 'nav-link' )  %>  
        </li>
      <% end %>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mooc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
    
  <div class="container" style="padding-top:20px;">
<%= yield %>
</div>
  </body>
</html>

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true, html: {class: 'form-horizontal'}) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field form-group">
    <%= form.label :title , class: 'col-sm-2 control-label' %>
     <div class="col-sm-10">
    <%= form.text_field :title, id: :lecture_title , class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group" >
    <%= form.label :content  , class: 'col-sm-2 control-label'%>
     <div class="col-sm-10" data-no-turbolink>
    <%= form.text_area :content, :class => 'ckeditor',  id: :lecture_content%>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :attachment , class: 'col-sm-2 control-label' %>
     <div class="col-sm-10">
    <%= form.file_field :attachment, id: :lecture_attachment , class: 'form-control' %>
    </div>
  </div>
<div class="field form-group">
    <%= form.label :course_id  , class: 'col-sm-2 control-label' %>
     <div class="col-sm-10">
     <%= form.select :course_id, options_for_select(Course.where(user_id: current_user.id).map{|s|[s.title, s.id]}) , class: 'form-control' %>
     </div>
  </div>
  <div class="actions form-group">
  <div class="col-sm-offset-2 col-sm-10">
   <%= form.submit 'Submit', :class=> 'btn btn-primary'%>
    </div>
  </div>
<% end %>

<%= javascript_include_tag  "//cdn.ckeditor.com/4.6.1/basic/ckeditor.js"%>

app/views/lectures/_like_link.html.erb
<%= link_to '<i style="color: red" class="fa fa-heart"></i> like'.html_safe, like_lecture_path(lecture), method: :put, remote: true,  id: "like-#{lecture.id}",class: 'btn btn-default' %>

app/views/lectures/_unlike_link.html.erb
<%= link_to '<i style="color: black" class="fa fa-heart"></i> unlike'.html_safe, unlike_lecture_path(lecture), method: :put, remote: true, id: "unlike-#{lecture.id}", class: 'btn btn-default' %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice" class="alert alert-error"><%= notice %></p>

<h1>Lectures</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>    
      <th>Content</th>
      <th>Attachment</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.title %></td>        
        <td><%= lecture.content.html_safe %></td>
        <td>
        <% if lecture.attachment? %>
        <% if File.extname(lecture.attachment.to_s)=='.jpeg'|| File.extname(lecture.attachment.to_s)=='.jpg'%>
        <%= image_tag(lecture.attachment.url, alt: 'Image',:size => "260x180") %>
        <% else %>
        <%= link_to lecture.attachment_url , class: "btn btn-success"  do %>
        <i class="fa fa-cloud-download"></i> Download Attachment
      <% end %>
        <% end %>
        <% end %>
        </td>
        <td><%= link_to lecture , class: "btn btn-info"  do %>
  <i class="fa fa-info-circle"></i> show

<%end%>
        <% if can? :update, lecture %>
        <%= link_to  edit_lecture_path(lecture) , class: "btn btn-warning" do %>
        <i class="fa fa-edit"></i> Edit
      <% end %>
       <%= link_to lecture, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
  <i class="fa fa-times"></i> Delete
<% end %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lectures/like.js.erb
$('#like-<%= @lecture.id %>').replaceWith('<%= escape_javascript render 'unlike_link', lecture: @lecture %>');
$('#like-count').html("<h4><%=@lecture.get_upvotes.size%> Likes</h4>");

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card ">
<div class="card-header bg-info text-white">
<h2><%= @lecture.title %> </h2>
</div>
 <div class="card-body">
 <div class="card-text">
  Course: <%= link_to @lecture.course.title, @lecture.course %>
</div>
<div class="card-text">
  Content: <%= @lecture.content.html_safe %>
</div>
<div>
<% if File.extname(@lecture.attachment.to_s)=='.jpeg'|| File.extname(@lecture.attachment.to_s)=='.jpg'%>
        <%= image_tag(@lecture.attachment.url, alt: 'Image',:size => "260x180") if @lecture.attachment? %>
        <% else %>
        <%= link_to "Download Attachment", @lecture.attachment_url if @lecture.attachment? %>
        <% end %>

  </div>
        
        <% if user_signed_in? %>
 <% if can? :update, @lecture %>
<%= link_to    edit_lecture_path(@lecture) , class: "btn btn-warning" do %>
        <i class="fa fa-edit"></i> Edit
      <% end %>  | 
<%= link_to  @lecture, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" do %>
  <i class="fa fa-times"></i> Delete
<% end %>  |
<%end%>

<%= link_to_if( ! @lecture.spam?(current_user), "Mark As Spam",  spam_lecture_path(@lecture)) {  "marked as a spam"} %>

<% if current_user.voted_as_when_voted_for @lecture  %>

  <%= render 'unlike_link', lecture: @lecture %>
<% else %> 

  <%= render 'like_link', lecture: @lecture %>
<% end %>
<% end %>
<div id="like-count"><h4><%= @lecture.get_upvotes.size %> Likes</h4></div>
<%= render partial: "comments/template", locals: {commentable: @lecture, new_comment: @comment} %>  
</div>
</div>

<%= link_to 'Back', :back %>

app/views/lectures/unlike.js.erb
$('#unlike-<%= @lecture.id %>').replaceWith('<%= escape_javascript render 'like_link', lecture: @lecture %>');
$('#like-count').html("<h4><%=@lecture.get_upvotes.size%> Likes</h4>");

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>